# Generated by Django 2.2.7 on 2019-11-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_process'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testomony',
            new_name='Testimony',
        ),
    ]
