# Generated by Django 2.2.7 on 2019-11-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20191112_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='description',
            field=models.TextField(default='describe here'),
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
