# Generated by Django 2.2.7 on 2019-11-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20191112_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
