# Generated by Django 2.2.7 on 2019-11-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_testimonyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
