# Generated by Django 2.2.7 on 2019-11-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_testimony_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
