# Generated by Django 2.2.7 on 2019-11-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20191112_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
