# Generated by Django 2.2.7 on 2019-11-15 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_packages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
