# Generated by Django 2.2.7 on 2019-11-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_schedule_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsingle',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
