# Generated by Django 2.2.7 on 2019-11-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_blogsingle_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
