# Generated by Django 2.2.7 on 2019-11-18 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20191115_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='day',
            new_name='training_type',
        ),
        migrations.AddField(
            model_name='schedule',
            name='coaches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='website.Coaches'),
        ),
    ]
