# Generated by Django 2.2.7 on 2019-11-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20191118_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='training_type',
        ),
        migrations.AddField(
            model_name='schedule',
            name='class_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classtype', to='website.ClassType'),
        ),
    ]
