# Generated by Django 2.2.7 on 2019-11-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20191118_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='class_type',
        ),
    ]
