# Generated by Django 2.2.7 on 2019-11-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20191119_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='day',
            new_name='days',
        ),
    ]
