# Generated by Django 2.2.7 on 2019-11-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20191119_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='days',
            new_name='day',
        ),
    ]
