# Generated by Django 2.2.7 on 2019-11-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20191119_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='coaches',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
