# Generated by Django 2.2.7 on 2019-11-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20191121_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coaches',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coaches',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
